### ISSUE TITLE
Changes Tracker

### ISSUE THREAD

**Issue by PinkShnack** [PinkShnack/curly_wurly#4]
Here is a list of new features we could have. If these are very difficult/detailed, we can open a specific issue for it.

- [ ] Create a way to add and delete blogs on the blog page.
- [ ] When you click on a blog it displays in its own page.
- [ ] Add category to blog details/object/contract.
- [ ] Add homepage with picture and carousel. 
- [ ] Add menu on right or left side to display snippets/highlights of other blogs.
- [ ] Think about layout and design
